POST http://localhost:3001/api/notes
Content-Type: application/json 

{
    "content": "Testing ----...",
    "important": true,
    "userId": "67c9db9f03ed2f4512364c79"
}

###
GET http://localhost:3001/api/notes