POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY3YzlkYjlmMDNlZDJmNDUxMjM2NGM3OSIsImlhdCI6MTc0MTI4ODE2MX0.z1oebaTT7zF6INUawCWYFcUann6Fh1wn1KvE_yR-Czw

{
    "content": "Testing 234----...",
    "important": true
}

###
GET http://localhost:3001/api/notes